print("")
nota1 = int(input("Digite a primeira nota: "))
nota2= int(input("Digite a segunda nota: "))
print("")
print(f"Primeira nota: {nota1};\nSegunda nota: {nota2};\nA média das duas notas é: {(nota1 + nota2)/2}.")