print("")
largura = float(input("Digite a largura da parede: ")) 
altura = float(input("Digite a altura da parede: "))
print("")
print(f"A área da parede é: {largura *  altura} m²;\nSerá necessário usar: {(largura * altura) / 2} litros de tinta")