print("")
salario = float(input("Qual é o salario do Funcionário? R$"))
print("")
novo_salario = salario + (salario * 0.15)
print(f"Um funcionário que ganhava R${salario}, com 15% de aumento, passa a receber R${novo_salario :.2f}")