print("")
largura = float(input("Largura da parede: "))
altura = float(input("Altura da parede: "))
print("")
print(f"Sua parede tem a dimensão de {largura} x {altura} e sua área é de {largura * altura}m².")
print(f"Para pintar essa parede, você precisará de {(largura * altura) / 2 :.2f} litros de tinta.")